import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

const dos = localFont({
  src: '../../public/fonts/DOSIyagiBoldface.ttf',
  display: 'swap',
  variable: '--font-dos',
})

export const metadata: Metadata = {
  title: "ER-api",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dos.variable}`}>
        {children}
      </body>
    </html>
  );
}
