import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { SeasonProvider } from './(home)/components/context/SeasonContext';


const dos = localFont({
  src: '../../public/fonts/DOSIyagiBoldface.ttf',
  display: 'swap',
  variable: '--font-dos',
})

export const metadata: Metadata = {
  title: "ER-api",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dos.variable}`}>
        <SeasonProvider>
          {children}
        </SeasonProvider>
      </body>
    </html>
  );
}
