import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { SeasonProvider } from './(home)/components/context/SeasonContext';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';


const dos = localFont({
  src: '../../../public/fonts/DOSIyagiBoldface.ttf',
  display: 'swap',
  variable: '--font-dos',
})

export const metadata: Metadata = {
  title: "ER-api",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${dos.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <SeasonProvider>
            {children}
          </SeasonProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
